import { Head, Link, router } from '@inertiajs/react';
import { Badge, Button, Group, Paper, Stack, Table, Text, Title } from '@mantine/core';
import AdminLayout from '@/layouts/AdminLayout';

export default function JourneyOperations({ rides, departures, demand, archive, purge, retention_days }: any) {
    return <AdminLayout title="Journey operations"><Head title="Journey operations" /><Stack gap="lg">
        <Group justify="space-between"><div><Title order={2}>Departures & dispatch</Title><Text c="dimmed">Assignments, unanswered requests and journey exceptions.</Text></div><Group><Button component={Link} href="/admin/settings" variant="default">Operational settings</Button><Button component={Link} href={`/admin/journey-operations?archive=${archive ? 0 : 1}`} variant="light">{archive ? 'Active requests' : 'Request archive'}</Button></Group></Group>
        <Paper p="md" withBorder><Title order={3}>Today’s departures</Title>{departures.map((a: any) => <Group key={a.id} justify="space-between" py="sm"><div><Text fw={600}>{a.schedule?.tour?.title}</Text><Text size="sm">{a.driver?.name || 'Driver unassigned'} · {a.vehicle?.registration_number || 'Vehicle pending'}</Text></div><Group><Badge>{a.status}</Badge>{a.vehicle && <Button component={Link} href={`/admin/vehicles/${a.vehicle.id}/tracking`} variant="subtle">GPS source & map</Button>}</Group></Group>)}</Paper>
        <Title order={3}>{archive ? 'Expired and superseded requests' : 'Active rides'}</Title>
        <Table.ScrollContainer minWidth={650}><Table striped><Table.Thead><Table.Tr><Table.Th>Booking</Table.Th><Table.Th>Customer / pickup</Table.Th><Table.Th>Journey</Table.Th><Table.Th>Payment</Table.Th><Table.Th>Driver</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{rides.data.map((r: any) => <Table.Tr key={r.id}><Table.Td><Link href={`/admin/ride-bookings/${r.id}`}>{r.booking_number}</Link></Table.Td><Table.Td>{r.customer_name}<Text size="xs">{r.pickup_location}</Text></Table.Td><Table.Td>{r.request_outcome || r.status}</Table.Td><Table.Td>{r.payment_status}</Table.Td><Table.Td>{r.driver?.name || 'Awaiting acceptance'}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Table.ScrollContainer>
        <Group>{rides.prev_page_url && <Button component={Link} href={rides.prev_page_url}>Previous</Button>}{rides.next_page_url && <Button component={Link} href={rides.next_page_url}>Next</Button>}</Group>
        <Paper withBorder p="md"><Group justify="space-between"><div><Title order={3}>Unanswered request retention</Title><Text>Delete eligible archived requests after {retention_days} days. Financial and assigned bookings are protected.</Text></div><Button variant="default" onClick={() => router.post('/admin/journey-operations/purge-preview')}>Preview eligible deletion</Button></Group>{purge && <Text mt="sm">{purge.dry_run ? 'Preview' : 'Last purge'}: {purge.eligible} eligible, {purge.deleted} deleted, {purge.protected} protected · {purge.at}</Text>}</Paper>
        {demand.length > 0 && <Paper p="md" withBorder><Title order={3}>Anonymous unmet demand after deletion</Title>{demand.map((row: any) => <Text key={row.id}>{row.day} · {row.service_type} · {row.outcome}: {row.requests} requests</Text>)}</Paper>}
    </Stack></AdminLayout>;
}
